# Generated by Django 3.2 on 2021-10-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityadmin',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='yellow_cards',
        ),
    ]
