# Generated by Django 3.2 on 2021-10-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('commission1', models.PositiveSmallIntegerField(default=0)),
                ('commission2', models.PositiveSmallIntegerField(default=0)),
                ('commission_employee1', models.PositiveSmallIntegerField(default=0)),
                ('commission_employee2', models.PositiveSmallIntegerField(default=0)),
                ('penalty', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['parent__id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('phonenums', models.JSONField(null=True)),
                ('other', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(max_length=24)),
                ('end', models.TimeField(max_length=24)),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه'), ('5', 'پنج شنبه'), ('6', 'جمعه')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
