# Generated by Django 3.2 on 2021-10-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapi', '0003_alter_timetablevisitor_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('5', 'شنبه'), ('6', 'یک شنبه'), ('0', 'دو شنبه'), ('1', 'سه شنبه'), ('2', 'چهار شنبه'), ('3', 'پنج شنبه'), ('4', 'جمعه')], max_length=1),
        ),
    ]
