# Generated by Django 3.2 on 2021-10-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequestvisitor',
            options={},
        ),
    ]
